name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: 'Build and Push'
    runs-on: ubunto-latest

    steps:
      - name: Checkout
        users: actions/checkout@v4

      - name: Generate sha
        id: genereta_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Build docker image
        run: docker build -t msusko/nlw.service.passin:${{ steps.generate_sha.outputs.sha }} .
